

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 latest-portfolio.glb 
*/

import React, { useState } from 'react'
import { useGLTF, OrthographicCamera, PerspectiveCamera } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/latest-portfolio.glb')
  
  return (
    <group {...props}  rotation={[0, Math.PI, 0]} dispose={null}>
      <OrthographicCamera makeDefault={props.activeCam === 0} zoom={85} far={1000} near={0.1} position={[-1.699, 10.565, -11.704]} rotation={[-2.944, -0.173, -3.107]} />
      <PerspectiveCamera makeDefault={props.activeCam === 1} far={1000} near={0.1} fov={51.631} position={[-8.521, 6.045, -1.489]} rotation={[-3.132, -0.645, -3.136]} scale={7.983} />
      <mesh onClick={()=>props.handlePartClick('monitor')} geometry={nodes.monitor.geometry} material={materials['monitor-material']} position={[-0.86, 6.013, 6.498]} scale={[1.56, 1.024, 0.16]} />
      <mesh onClick={()=>props.handlePartClick('white-board')} geometry={nodes.Cube001.geometry} material={materials['white-board-material']} position={[-3.85, 9.001, 7.148]} scale={[1.635, 2.379, 0.065]} />
      <mesh geometry={nodes.Blinds.geometry} material={materials['blinds-material']} position={[1.969, 10.709, 6.972]} rotation={[0.005, -0.001, -0.002]} scale={[3.455, 0.494, 0.137]} />
      <mesh geometry={nodes.Sphere006.geometry} material={materials['cat-body']} position={[4.402, 6.726, 7.701]} rotation={[0, 0, 0.387]} scale={[0.922, 0.686, 0.615]} />
      <mesh geometry={nodes.BézierCurve.geometry} material={materials['cat-tail']} position={[4.603, 6.243, 7.412]} rotation={[0, 0, 0.053]} scale={0.644} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['wall-material']} position={[-2.05, 9.767, 2.391]} scale={[11.23, 9.087, 4.841]} />
      <mesh geometry={nodes.record.geometry} onClick={()=>props.handlePartClick('record')} material={materials['Material.002']} position={[6.458, 7.143, 5.467]} rotation={[0, 0.629, 0]} scale={[0.057, 0.031, 0.115]} />
      <mesh geometry={nodes['cat-head002'].geometry} material={materials['cat-eyes']} position={[3.254, 6.918, 7.473]} rotation={[0.052, -0.778, 0.502]} scale={[-0.127, -0.155, -0.137]} />
      <group position={[8.509, 4.337, 5.722]} rotation={[Math.PI / 2, 0, -0.896]} scale={[0.359, 0.358, 0.463]}>
        <mesh geometry={nodes.Plane003.geometry} material={materials['cactus-pot-material']} />
        <mesh geometry={nodes.Plane003_1.geometry} material={materials['cactus-material']} />
        <mesh geometry={nodes.Plane003_2.geometry} material={materials['file-cabinet-material']} />
      </group>
      <group position={[7.395, 10.116, 7.01]} rotation={[1.881, -1.554, 1.743]} scale={[0.048, 0.507, 0.507]}>
        <mesh geometry={nodes.Cube320.geometry} material={materials['paint-bottle-1']} />
        <mesh geometry={nodes.Cube320_1.geometry} material={materials['canvas-material']} />
        <mesh geometry={nodes.Cube320_2.geometry} material={materials['paint-material-4']} />
        <mesh geometry={nodes.Cube320_3.geometry} material={materials['paint-material-3']} />
        <mesh geometry={nodes.Cube320_4.geometry} material={materials['paint-material-2']} />
        <mesh geometry={nodes.Cube320_5.geometry} material={materials['shelf-material']} />
        <mesh geometry={nodes.Cube320_6.geometry} material={materials['plant-pot']} />
        <mesh geometry={nodes.Cube320_7.geometry} material={materials['plant-material']} />
      </group>
      <group position={[6.491, 7.143, 5.575]} rotation={[0, 0.629, 0]} scale={[0.057, 0.031, 0.115]}>
        <mesh geometry={nodes.Cube673.geometry} material={materials['record-cover-material']} />
        <mesh geometry={nodes.Cube673_1.geometry} material={materials['record-needle-material']} />
        <mesh geometry={nodes.Cube673_2.geometry} material={materials['record-button-material']} />
        <mesh geometry={nodes.Cube673_3.geometry} material={materials['record-body-material']} />
        <mesh geometry={nodes.Cube673_4.geometry} material={materials['record-turntable-material']} />
        <mesh geometry={nodes.Cube673_5.geometry} material={materials['shelf-material']} />
      </group>
      <mesh geometry={nodes['filing-cabinet020'].geometry} material={nodes['filing-cabinet020'].material} position={[8.336, 4.337, 5.722]} rotation={[Math.PI / 2, 0, -0.896]} scale={[0.359, 0.358, 0.463]} />
      <group position={[8.509, 4.337, 5.722]} rotation={[Math.PI / 2, 0, -0.896]} scale={[0.359, 0.358, 0.463]}>
        <mesh geometry={nodes.Plane032.geometry} material={materials['college-banner-material']} />
        <mesh onClick={()=>props.handlePartClick('diploma')} geometry={nodes.Plane032_1.geometry} material={materials['diploma-material']} />
      </group>
      <group position={[2.179, 4.865, 5.151]} rotation={[2.977, 0, -Math.PI]} scale={[-1.035, -0.037, -0.382]}>
        <mesh geometry={nodes.Cube2257.geometry} material={materials['desktop-material']} />
        <mesh geometry={nodes.Cube2257_1.geometry} material={materials['desk-mat-material']} />
        <mesh geometry={nodes.Cube2257_2.geometry} material={materials['keyboard-base-material']} />
        <mesh geometry={nodes.Cube2257_3.geometry} material={materials['white-key-material']} />
        <mesh geometry={nodes.Cube2257_4.geometry} material={materials['grey-key-material']} />
        <mesh geometry={nodes.Cube2257_5.geometry} material={materials['red-key-material']} />
        <mesh geometry={nodes.Cube2257_6.geometry} material={materials['green-key-material']} />
        <mesh geometry={nodes.Cube2257_7.geometry} material={materials['desk-material']} />
        <mesh geometry={nodes.Cube2257_8.geometry} material={materials['book-4-material']} />
        <mesh geometry={nodes.Cube2257_9.geometry} material={materials['book-3-material']} />
        <mesh geometry={nodes.Cube2257_10.geometry} material={materials['book-1-material']} />
        <mesh geometry={nodes.Cube2257_11.geometry} material={materials['book-2-material']} />
      </group>
      <mesh geometry={nodes['cat-head003'].geometry} material={materials['cat-head']} position={[3.254, 6.918, 7.473]} rotation={[0.052, -0.778, 0.502]} scale={[-0.127, -0.155, -0.137]} />
      <mesh geometry={nodes['cat-head008'].geometry} material={materials['cat-pupils']} position={[3.254, 6.918, 7.473]} rotation={[0.052, -0.778, 0.502]} scale={[-0.127, -0.155, -0.137]} />
      <group position={[-5.948, 8.206, 6.781]} rotation={[1.739, -1.496, 3.021]} scale={0.024}>
        <mesh geometry={nodes.Cylinder371.geometry} material={materials['bass-tuning-material']} />
        <mesh geometry={nodes.Cylinder371_1.geometry} material={materials['bass-button-material']} />
        <mesh geometry={nodes.Cylinder371_2.geometry} material={materials['bass-body-material']} />
        <mesh geometry={nodes.Cylinder371_3.geometry} material={materials['bass-pickup-material']} />
        <mesh geometry={nodes.Cylinder371_4.geometry} material={materials['bass-string-material']} />
        <mesh geometry={nodes.Cylinder371_5.geometry} material={materials['bass-neck-material']} />
        <mesh geometry={nodes.Cylinder371_6.geometry} material={materials['bass-fret-material']} />
      </group>
      <group position={[-4.913, 5.62, 7.082]} rotation={[-1.583, 0, -Math.PI]} scale={[-0.156, -0.024, -0.269]}>
        <mesh geometry={nodes.Cube289.geometry} material={materials['marker-holder-material']} />
        <mesh geometry={nodes.Cube289_1.geometry} material={materials['eraser-material']} />
        <mesh geometry={nodes.Cube289_2.geometry} material={materials['black-marker-material']} />
        <mesh geometry={nodes.Cube289_3.geometry} material={materials['blue-marker-material']} />
        <mesh geometry={nodes.Cube289_4.geometry} material={materials['red-marker-material']} />
        <mesh geometry={nodes.Cube289_5.geometry} material={materials['green-marker-material']} />
      </group>
    </group>
  )
}

useGLTF.preload('/latest-portfolio.glb')
